workerman:
    # 服务配置
    server:
        # 进程名称
        name: 'Symfony Workerman Server'
        # 监听的协议 ip 及端口 （可选）
        listen: http://0.0.0.0:8000
        # 进程数 （可选，默认1）
        count: ~
        # 进程运行用户 （可选，默认当前用户）
        user: ''
        # 进程运行用户组 （可选，默认当前用户组）
        group: ''
        # 当前进程是否支持reload （可选，默认true）
        reloadable: true
        # 是否开启reusePort （可选，此选项需要php>=7.0，默认为true）
        reusePort: true
        # transport (可选，当需要开启ssl时设置为ssl，默认为tcp)
        transport: tcp
        # context （可选，当transport为是ssl时，需要传递证书路径）
        context: []
        # After sending the stop command to the child process stopTimeout seconds,
        # if the process is still living then forced to kill.
        stopTimeout: 2
        # The file to store master process PID.
        pidFile: '%kernel.project_dir%/var/workerman.pid'
        # Log file.
        logFile: '%kernel.project_dir%/var/log/workerman.log'
        # The file used to store the master process status file.
        statusFile: '%kernel.project_dir%/var/log/workerman.status'
        # Stdout file.
        stdoutFile: '%kernel.project_dir%/var/log/workerman.stdout.log'
